### ISSUE TITLE
梯度下降与更新

### ISSUE THREAD

**Issue by penbury** [Site1997/LeNet-python#1]
你好，我在运行你的代码时，有两处不理解的地方。
1. 梯度下降求kernal gradient时：
你的代码：
kernal_gradient[kId][cId] += convolve2d(front_delta[imgId][kId], input_map[imgId, cId, ::-1, ::-1])
我觉得直接这样就可以了：
kernal_gradient[kId][cId] = convolve2d(input_map[imgId, cId], front_delta[imgId][kId])
参考链接：https://www.cnblogs.com/pinard/p/6494810.html

2. 梯度更新时：
你的代码：
kernal += self.lr * kernal_gradient  # why add？ why not sub?

期待你的回复！谢谢！

**Comment by Site1997** [comment]
Answered in another thread.
