### ISSUE TITLE
gradient descent and update

### ISSUE THREAD

**Issue by penbury** [Site1997/LeNet-python#2]
Hello, when I ran your code, I had two questions. Help me, Please.

The first one is about the gradient of the kernal:
Your code look like this: 
kernal_gradient[kId][cId] += convolve2d(front_delta[imgId][kId], input_map[imgId, cId, ::-1, ::-1])
I think:
kernal_gradient[kId][cId] = convolve2d(input_map[imgId, cId], front_delta[imgId][kId])
refrence linking: https://www.cnblogs.com/pinard/p/6494810.html

The second one is about the updates of the kernal:
Your code look like this: 
kernal += self.lr * kernal_gradient # why add？ why not sub?

Look forward to your reply, thanks!

**Comment by Site1997** [comment]
1. Notice that, there is a "rot180" symbol in the link you gave me, meaning that the kernal should be reversed 180 degrees. 
2. See below, I use **(y_true - y_pred)** instead of **(y_pred - y_true)** when calculating l8_delta. That's why I use '+' instead of '-' to update every weight in CNN.
```
l8_delta  = (output_label - softmax_output) / softmax_output.shape[0]
```
